name: Collections Package Test

on:
  push:
    paths:
      - 'collections/**'
      - '.github/workflows/collections-test.yml'
  pull_request:
    paths:
      - 'collections/**'
      - '.github/workflows/collections-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '3.0.3'

      - name: Install dependencies
        working-directory: ./collections
        run: |
          npm install -g npm@latest
          npm install simpl-schema

      - name: Run package tests
        working-directory: ./collections
        run: |
          export NODE_PATH=$(npm root -g)
          meteor test-packages ./
